pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://repository.hanbings.io/proxy' }
        maven { url 'https://maven.architectury.dev/' }
        maven { url 'https://neoforged.forgecdn.net/releases/' }
        maven { url 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'diggusmaximus'

include(':neoforge')
